version: "3"

services:
  website:
    build:
      context: ./
      dockerfile: ./.docker/production/website/Dockerfile
    container_name: kenan_website_dev
    restart: unless-stopped
    ports:
      - 8803:3000
    networks:
      - kenan_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  kenan_network: